 
CREATE TABLE IF NOT EXISTS BENEFICIO (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  SALDO DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  ATIVO BOOLEAN DEFAULT TRUE,
  DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DT_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  VERSION BIGINT NOT NULL DEFAULT 0
);

-- Índices
CREATE INDEX IF NOT EXISTS IDX_BENEFICIO_NOME ON BENEFICIO (NOME);
CREATE INDEX IF NOT EXISTS IDX_BENEFICIO_ATIVO ON BENEFICIO (ATIVO);

 

CREATE TABLE IF NOT EXISTS TRANSFERENCIA (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_ORIGEM BIGINT NOT NULL,
  ID_DESTINO BIGINT NOT NULL,
  VALOR DECIMAL(15,2) NOT NULL,
  DT_TRANSFERENCIA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  STATUS VARCHAR(20) DEFAULT 'SUCESSO',
  IDEMPOTENCY_KEY VARCHAR(64),
  CONSTRAINT FK_TRANSFER_ORIGEM FOREIGN KEY (ID_ORIGEM) REFERENCES BENEFICIO(ID),
  CONSTRAINT FK_TRANSFER_DESTINO FOREIGN KEY (ID_DESTINO) REFERENCES BENEFICIO(ID)
);

 
CREATE INDEX IF NOT EXISTS IDX_TRANSFERENCIA_ORIGEM ON TRANSFERENCIA (ID_ORIGEM);
CREATE INDEX IF NOT EXISTS IDX_TRANSFERENCIA_DESTINO ON TRANSFERENCIA (ID_DESTINO);
CREATE INDEX IF NOT EXISTS IDX_TRANSFERENCIA_IDEMPOTENCY ON TRANSFERENCIA (IDEMPOTENCY_KEY);
